### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by sophieyoung717** [mljs/naive-bayes#1]
Hi, sorry but I am new at this.

I test the package by running "require("ml-naivebayes")"  in the browser, I got an error saying: 

/app/available_modules/1465234699000/ml-naivebayes/node_modules/ml-matrix/src/matrix.js:6
class Matrix extends Array {
^^^^^
Unexpected reserved word

Is your package or exactly how to require your package and run?

**Comment by maasencioh** [comment]
Hello @sophieyoung717, are you running it in Tonic? If that's true you should check that it's running in the NodeJS version v4.4.5 or superior.

Also if you prefer we can add an example in Tonic by default.

Thanks!
