### ISSUE TITLE
web version seems not working

### ISSUE THREAD

**Issue by jack1232** [mljs/naive-bayes#11]
when using the web version with the command:

var model = new ML.GaussianNB();  

I got the error: ML.GaussianNB is not a constructor.  For ML.MultinomialNB, I got the same error.

How to use Naive Bayes model for the web version?

**Comment by maasencioh** [comment]
Hello, how are you importing the ML library?

**Comment by jack1232** [comment]
<script src="https://www.lactame.com/lib/ml/3.2.0/ml.min.js"></script>
as mentioned in the introduction. 

Also I tried: var model = new ML.DecisionTreeClassifier(options); it works. However:
var model = new ML.DecisionTreeRegression(), it also gives the error:ML. DecisionTreeRegression is not a constructor.

**Comment by stropitek** [comment]
For the decision tree, it was fixed in https://github.com/mljs/ml/commit/c5df0dac9171bcb4fb7fa0b18d54f01007eb8383 but is not yet released.
For NaiveBayes, it is in `ML.NaiveBayes`. So for example GaussianNB is in `ML.NaiveBayes.GaussianNB`

**Comment by targos** [comment]
I just published version 3.3.0 that should fix the DecisionTreeRegression

**Comment by jack1232** [comment]
thanks
