### ISSUE TITLE
Bug with more than 2 features

### ISSUE THREAD

**Issue by hseung** [mljs/naive-bayes#3]
Hi, 

I came to realize that a bug may exist in a current code base.

First of all, I have little knowledge of naive bayes or other things about machine learning but noticed the issue while using this library with 3 features.

Things were fine until with 2 features, but i found that third feature is not working on prediction when increasing the number of features to 3.

I may have a solution for this with details in https://github.com/hseung/naive-bayes/pull/1 but wanted your confirmation before submitting this.

Please look through this and let me know your opinion on this.

Thanks.

**Comment by targos** [comment]
@JeffersonH44 can you have a look ?

**Comment by JeffersonH44** [comment]
ok, I will check

**Comment by JeffersonH44** [comment]
yes, there is a mistake with the usage of more variables, I also make the test with the sklearn implementation of Gaussian Bayes and it should work the 3 variables case, so I don't know if @hseung can make the pull request with those changes
